In [1]:
import numpy as np

In [2]:
import pandas as pd

In [8]:
df=pd.read_csv(r'C:\Users\Muhd\Desktop\examples\Data_for_UCI_named.csv')

In [9]:
df.head(4)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable

In [12]:
df=df.drop('stab', axis=1)

In [13]:
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [14]:
X = df.drop(columns='stabf')

In [15]:
X

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  
1    -1.255012  0.413441  0.862414  0.562139  0.781760  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  
...        ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  

[10000 rows x 12 columns]

In [16]:
y = df['stabf']

In [17]:
y

0       unstable
1         stable
2       unstable
3       unstable
4       unstable
          ...   
9995    unstable
9996      stable
9997      stable
9998    unstable
9999    unstable
Name: stabf, Length: 10000, dtype: object

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [36]:
y_train

2694    unstable
5140    unstable
2568    unstable
3671    unstable
7427    unstable
          ...   
2895      stable
7813      stable
905     unstable
5192    unstable
235       stable
Name: stabf, Length: 8000, dtype: object

In [37]:
y_test

9953    unstable
3850    unstable
4962      stable
3886      stable
5437    unstable
          ...   
3919      stable
162       stable
7903      stable
2242    unstable
2745    unstable
Name: stabf, Length: 2000, dtype: object

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler = MinMaxScaler()

In [26]:
normalised_df = scaler.fit_transform(x_train)

In [28]:
normalised_df = pd.DataFrame(normalised_df, columns=x_train.columns)

In [29]:
normalised_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.605895  0.214898  0.686826  0.945002  0.454782  0.516700  0.874552   
1     0.481097  0.525305  0.797470  0.027436  0.616162  0.479547  0.065178   
2     0.075724  0.874245  0.355155  0.835240  0.474432  0.640493  0.697645   
3     0.736693  0.652439  0.873580  0.171161  0.362461  0.278625  0.940452   
4     0.692014  0.088023  0.589553  0.764197  0.220544  0.718310  0.911640   
...        ...       ...       ...       ...       ...       ...       ...   
7995  0.947942  0.501630  0.160952  0.792326  0.436067  0.718167  0.315786   
7996  0.793271  0.434989  0.071276  0.074168  0.586343  0.287753  0.786719   
7997  0.689756  0.290888  0.095294  0.420814  0.504170  0.914034  0.394700   
7998  0.482641  0.135673  0.209040  0.247169  0.368319  0.738076  0.649711   
7999  0.074175  0.683759  0.571667  0.213023  0.851865  0.163169  0.288036   

            p4        g1        g2        g3        g4  
0     0.255448  0.545528  0.598331  0.669360  0.642234  
1     0.641255  0.414248  0.049680  0.912824  0.083403  
2     0.252484  0.903588  0.919622  0.198830  0.642306  
3     0.691134  0.221930  0.893734  0.963154  0.579607  
4     0.685474  0.983833  0.701163  0.828559  0.121206  
...        ...       ...       ...       ...       ...  
7995  0.666197  0.149332  0.590851  0.031541  0.316121  
7996  0.196614  0.182514  0.281840  0.712410  0.412244  
7997  0.197039  0.861431  0.584817  0.053214  0.734067  
7998  0.505777  0.446253  0.387895  0.290830  0.981638  
7999  0.061853  0.854751  0.160771  0.840609  0.726354  

[8000 rows x 12 columns]

In [31]:
normalised_test_df = scaler.transform(x_test)

In [32]:
normalised_test_df = pd.DataFrame(normalised_test_df, columns=x_test.columns)

In [68]:
normalised_test_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.671365  0.380367  0.932340  0.821112  0.577835  0.068198  0.272932   
1     0.558188  0.607557  0.445405  0.349467  0.466385  0.193555  0.621676   
2     0.188048  0.408938  0.245239  0.504652  0.339393  0.531448  0.732018   
3     0.475764  0.179892  0.606958  0.008257  0.639912  0.026362  0.616975   
4     0.752247  0.914666  0.524646  0.993199  0.479150  0.496922  0.443090   
...        ...       ...       ...       ...       ...       ...       ...   
1995  0.823245  0.304608  0.101903  0.870290  0.550590  0.267173  0.712675   
1996  0.188375  0.266085  0.797001  0.596885  0.476900  0.597305  0.786062   
1997  0.773597  0.019302  0.023944  0.652999  0.237538  0.957730  0.526629   
1998  0.176148  0.555478  0.431308  0.621034  0.300516  0.712074  0.508036   
1999  0.101785  0.935851  0.581024  0.934445  0.621186  0.069982  0.273930   

            p4        g1        g2        g3        g4  
0     0.954195  0.238500  0.837447  0.065691  0.813278  
1     0.798284  0.028968  0.385755  0.908498  0.854065  
2     0.712638  0.920287  0.084360  0.688470  0.014509  
3     0.474772  0.523093  0.016780  0.397283  0.804946  
4     0.637113  0.538482  0.075332  0.776320  0.263485  
...        ...       ...       ...       ...       ...  
1995  0.393297  0.639455  0.466717  0.135680  0.129710  
1996  0.200205  0.774360  0.758130  0.193996  0.184273  
1997  0.782590  0.142234  0.536636  0.665863  0.881011  
1998  0.867006  0.939725  0.729610  0.107517  0.268611  
1999  0.827655  0.641638  0.234936  0.501312  0.843387  

[2000 rows x 12 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
encoder = LabelEncoder()

In [38]:
y_train = encoder.fit_transform(y_train)

In [43]:
y_test= encoder.transform(y_test)

In [69]:
y_train

array([1, 1, 1, ..., 1, 1, 0])

In [70]:
y_test

array([1, 1, 0, ..., 0, 1, 1])

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
dec_tree = DecisionTreeClassifier()

In [48]:
dec_tree.fit(normalised_df, y_train)

DecisionTreeClassifier()

In [60]:
#pip install xgboost

In [61]:
import xgboost as xgb

In [62]:
regressor = xgb.XGBRegressor()

In [63]:
regressor.fit(normalised_df, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [64]:
normalised_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.605895  0.214898  0.686826  0.945002  0.454782  0.516700  0.874552   
1     0.481097  0.525305  0.797470  0.027436  0.616162  0.479547  0.065178   
2     0.075724  0.874245  0.355155  0.835240  0.474432  0.640493  0.697645   
3     0.736693  0.652439  0.873580  0.171161  0.362461  0.278625  0.940452   
4     0.692014  0.088023  0.589553  0.764197  0.220544  0.718310  0.911640   
...        ...       ...       ...       ...       ...       ...       ...   
7995  0.947942  0.501630  0.160952  0.792326  0.436067  0.718167  0.315786   
7996  0.793271  0.434989  0.071276  0.074168  0.586343  0.287753  0.786719   
7997  0.689756  0.290888  0.095294  0.420814  0.504170  0.914034  0.394700   
7998  0.482641  0.135673  0.209040  0.247169  0.368319  0.738076  0.649711   
7999  0.074175  0.683759  0.571667  0.213023  0.851865  0.163169  0.288036   

            p4        g1        g2        g3        g4  
0     0.255448  0.545528  0.598331  0.669360  0.642234  
1     0.641255  0.414248  0.049680  0.912824  0.083403  
2     0.252484  0.903588  0.919622  0.198830  0.642306  
3     0.691134  0.221930  0.893734  0.963154  0.579607  
4     0.685474  0.983833  0.701163  0.828559  0.121206  
...        ...       ...       ...       ...       ...  
7995  0.666197  0.149332  0.590851  0.031541  0.316121  
7996  0.196614  0.182514  0.281840  0.712410  0.412244  
7997  0.197039  0.861431  0.584817  0.053214  0.734067  
7998  0.505777  0.446253  0.387895  0.290830  0.981638  
7999  0.061853  0.854751  0.160771  0.840609  0.726354  

[8000 rows x 12 columns]

In [65]:
y_train

array([1, 1, 1, ..., 1, 1, 0])